---
- name: regolith ~> Ensure use regolith 2.0 on new dist
  block:
    - name: Ensure apt key present
      ansible.builtin.apt_key:
        url: https://regolith-desktop.io/regolith.key
        keyring: /etc/apt/trusted.gpg.d/regolith-archive-keyring.gpg
        state: present
    - name: Ensrue apt repository present and cache updated
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://regolith-desktop.io/release-{{ os_dist }}-{{ os_release }}-amd64 {{ os_release }} main"
        filename: "regolith"
        update_cache: yes
  when: os_release in ["bullseye", "focal", "jammy"]

- name: regolith ~> Ensure use regolith 1.6 on older dist
  block:
    - name: Ensure apt repo ppa added
      ansible.builtin.apt_repository:
        repo: ppa:regolith-linux/release
    - name: Ensure regolith package name configured
      ansible.builtin.set_fact:
        regolith_package: regolith-desktop-standard
  when: os_release not in ["bullseye", "focal", "jammy"]

- name: regolith ~> Ensure package installed
  ansible.builtin.package:
    name: "{{ regolith_package }}"
    state: present
