---
- name: proxy ~> Ensure cert file copied
  ansible.builtin.copy:
    src: "{{ proxy_cert }}"
    dest: "{{ cert_path }}/{{ proxy_cert|basename }}"
    mode: "0644"
  when: ansible_os_family == 'Debian'

#- name: proxy ~> Ensure cert file copied on RedHat family OS
#  ansible.builtin.copy:
#    src: "{{ proxy_cert }}"
#    dest: "/etc/ssl/certs/{{ proxy_cert | basename | replace('.crt', '.pem') }}"
#    mode: "0644"
#  when: ansible_os_family == 'RedHat'

- name: proxy ~> Ensure update cert executed
  ansible.builtin.command:
    cmd: "{{ update_cert_command }}"
    creates: "{{ proxy_cert_path }}"
  register: out
  changed_when: false
