---
- name: Ensure package install tasks included
  ansible.builtin.include_tasks:
    file: "{{ shell_tasks.name }}/setup.yml"
    apply:
      become: true
      become_user: "{{ user }}"
  when: shell_tasks.check
  loop: "{{ shell_packages }}"
  loop_control:
    loop_var: shell_tasks
    label: "{{ shell_tasks.name }}"

- name: Ensure fish config dir exists
  when: fish
  ansible.builtin.file:
    path: "{{ fish_config | dirname }}"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user_group }}"

- name: Ensure zshrc exists
  when: zsh
  ansible.builtin.copy:
    src: /etc/zsh/zshrc
    remote_src: yes
    dest: "{{ zshrc }}"
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0644"
    force: no

- name: Ensure zprofile exists
  when: zsh
  ansible.builtin.copy:
    src: /etc/zsh/zprofile
    remote_src: yes
    dest: "{{ zsh_profile }}"
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0644"
    force: no

- name: Ensure fish config exists
  when: fish
  ansible.builtin.copy:
    src: /etc/fish/config.fish
    remote_src: yes
    dest: "{{ fish_config }}"
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0644"
    force: no
