---
- name: Ensure package install tasks included
  ansible.builtin.include_tasks:
    file: "{{ shell_tasks.name }}/setup.yml"
    apply:
      become: true
      become_user: "{{ user }}"
  when: shell_tasks.check and build_shell
  loop: "{{ shell_packages }}"
  loop_control:
    loop_var: shell_tasks
    label: "{{ shell_tasks.name }}"
