---
- name: vagrant ~> Ensure setup task for {{ ws_os_family }} included
  ansible.builtin.include_tasks: vagrant/setup-{{ ws_os_family }}.yml

- name: vagrant ~> Ensure package installed
  ansible.builtin.package:
    name: vagrant
    state: present
