---
namespace: kilip
name: workstation
version: 1.0.5
readme: README.md
authors:
  - Anthonius Munthi <me@itstoni.com>
description: Collection of workstation automation tools for Ansible
license:
  - MIT
tags:
  - homebrew
  - linuxbrew
  - brew
  - workstation
  - dev
  - mas
  - configure
  - development

dependencies:
  ansible.posix: "*"
  community.general: ">=3.0.0"
  community.sops: ">=1.2.2"

repository: https://github.com/kilip/ansible-role-workstation
documentation: https://github.com/kilip/ansible-role-workstation/wiki
homepage: https://github.com/kilip/ansible-role-workstation
issues: https://github.com/kilip/ansible-role-workstation/issues

build_ignore:
  - .github
  - .taskfiles
  - .vscode
  - .molecule
  - .editorconfig
  - .envrc
  - .pre-commit-config.yaml
  - ansible.cfg
  - requirements.txt
  - Taskfile.yml
