---
version: '3'

includes:
  test: .taskfiles/TestTasks.yml

vars:
  WS_FILES_DIR: "{{.PROJECT_DIR}}/files"
tasks:
  deps:
    cmds:
      - pre-commit install

  sops:encrypt:
    desc: Encrypt files
    cmds:
      - mkdir -p $(dirname {{.FULL_DEST}})
      - cp {{.SRC}} {{.FULL_DEST}}
      - sops -i -e --config {{.SOPS_CONFIG_FILE}} {{.FULL_DEST}}
      - echo "encrypted file to files/{{.DEST}}"
    vars:
      SRC: '{{ (split " " .CLI_ARGS)._0 }}'
      DEST: '{{ (split " " .CLI_ARGS)._1 }}'
      FULL_DEST: "{{.WS_FILES_DIR}}/{{.DEST}}"

  export:gpg:
    desc: Export your gpg keys with given id
    cmds:
      - mkdir -p $(dirname {{.target}})
      - gpg --export-secret-keys {{.CLI_ARGS}} > {{.tempfile}}
      - cp {{.tempfile}} {{.target}}
      - ansible-vault encrypt {{.target}}
      - rm {{.tempfile}}
      - echo "exported to gpg/{{.filename}}"
    vars:
      filename: gpg-{{.CLI_ARGS}}.key
      tempfile: /tmp/{{.filename}}
      target: '{{.WS_FILES_DIR}}/gpg/{{.filename}}'

  build:
    cmds:
      - ansible-playbook kilip.workstation.deps -vvvvv
