---
- name: facts ~> Ensure tasks configured
  ansible.builtin.set_fact:
    gpg_import: "{{ user_gpg_keys | length > 0 }}"
    ssh_import: "{{ user_ssh_keys | length > 0 }}"

- name: facts ~> Ensure chezmoi configured
  ansible.builtin.set_fact:
    chezmoi_init: "{{ chezmoi_repo | length > 0 }}"
    chezmoi_install: "{{ 'chezmoi' not in brew_packages or not build_brew }}"
    chezmoi_bin: "{{ ('chezmoi' in brew_packages and build_brew) and brew_prefix + '/bin/chezmoi' or user_home + '/bin/chezmoi' }}"

- name: facts ~> Ensure chezmoi brew packages
  kilip.workstation.add_package:
    brew: chezmoi
  when: not chezmoi_install

- name: facts ~> Ensure user facts configured
  ansible.builtin.set_fact:
    user_configure_shell: "{{ user_shell | length > 0 }}"
    user_configure_git: "{{ git_config | length > 0 }}"

- name: facts ~> Ensure gnupg installed
  kilip.workstation.add_package:
    package: gnupg
