---
- name: facts ~> Ensure executed user tasks configured
  ansible.builtin.set_fact:
    gpg_import: "{{ user_gpg_keys | length > 0 }}"
    ssh_import: "{{ user_ssh_keys | length > 0 }}"

- name: facts ~> Ensure gpg keys configuration valid
  ansible.builtin.assert:
    that:
      - "'id' in item"
      - "'file' in item"
    fail_msg: User gpg Keys item should contains id and file format.
    quiet: true
  loop: "{{ user_gpg_keys }}"
  no_log: true

- name: facts ~> Ensure ssh public key exists
  ansible.builtin.assert:
    that:
      - "{{ lookup('file', encrypted_dir + '/' + item + '.pub' ) | length > 0 }}"
    fail_msg: User ssh public key file "{{ item }}.pub" should exists
    quiet: true
  loop: "{{ user_ssh_keys }}"

- name: facts ~> Ensure user is configured
  ansible.builtin.assert:
    that: user | length > 0
    quiet: true
    fail_msg: user variable should be configured

- name: facts ~> Ensure chezmoi configured
  ansible.builtin.set_fact:
    chezmoi_init: "{{ chezmoi_repo | length > 0 }}"
    chezmoi_install: "{{ 'chezmoi' not in brew_packages or not brew }}"
    chezmoi_bin: "{{ ('chezmoi' in brew_packages and brew) and brew_prefix + '/bin/chezmoi' or user_home + '/bin/chezmoi' }}"

- name: facts ~> Ensure chezmoi installed in brew packages
  kilip.workstation.add_package:
    brew: chezmoi
  when: chezmoi_init
