---
- name: preflight ~> Ensure gpg keys are imported
  ansible.builtin.include_tasks: gpg/setup.yml
  when: gpg_import

- name: Ensure chezmoi setup tasks included
  when: chezmoi_init
  ansible.builtin.include_tasks: chezmoi/setup.yml
