---
- name: preflight ~> Ensure user group exists
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: present

- name: preflight ~> Ensure user exist
  ansible.builtin.user:
    name: "{{ user }}"
    home: "{{ user_home }}"
    group:  "{{ user_group }}"
    state: present
    shell: "{{ user_shell }}"

- name: preflight ~> Ensure shared dir exists
  ansible.builtin.file:
    path: "{{ workstation_shared_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0755"

- name: preflight ~> Ensure ssh keys imported
  ansible.builtin.include_tasks: ssh/setup.yml
  when: ssh_import

- name: Ensure curl configured
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.curlrc"
    line: "insecure"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
    create: true
  when: proxy_cert_build

- name: Ensure remote temp dir exists
  ansible.builtin.file:
    path: "{{ ansible_remote_tmp }}"
    state: directory
    mode: "0777"
    owner: "{{ user }}"
    group: "{{ user_group }}"
  when: ansible_remote_tmp is defined
