---
- name: preflight ~> Ensure user group exists
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: present

- name: preflight ~> Ensure user exist
  ansible.builtin.user:
    name: "{{ user }}"
    home: "{{ user_home }}"
    group:  "{{ user_group }}"
    state: present
    shell: /bin/bash

- name: preflight ~> Ensure ssh keys imported
  ansible.builtin.include_tasks: ssh/setup.yml
  when: ssh_import

- name: preflight ~> Ensure gpg deps packages is installed
  kilip.workstation.add_package:
    package: gnupg
