---
- name: assert ~> Ensure gpg keys configuration valid
  ansible.builtin.assert:
    that:
      - "'id' in item"
      - "'file' in item"
    fail_msg: User gpg Keys item should contains id and file format.
    quiet: true
  loop: "{{ user_gpg_keys }}"
  no_log: true

- name: assert ~> Ensure ssh public key exists
  ansible.builtin.assert:
    that:
      - "{{ lookup('file', item + '.pub' ) | length > 0 }}"
    fail_msg: User ssh public key file "{{ item }}.pub" should exists
    quiet: true
  loop: "{{ user_ssh_keys }}"

- name: assert ~> Ensure user is configured
  ansible.builtin.assert:
    that: user | length > 0
    quiet: true
    fail_msg: user variable should be configured
