---
- name: ssh ~> Ensure keys dir exists
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ user }}"
    group: "{{ user_group }}"

- name: ssh ~> Ensure private keys imported
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ user_home }}/.ssh/{{ item | basename }}"
    mode: "0600"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop: "{{ user_ssh_keys }}"

- name: ssh ~> Ensure public keys imported
  ansible.builtin.copy:
    src: "{{ item }}.pub"
    dest: "{{ user_home }}/.ssh/{{ item | basename }}.pub"
    mode: "0600"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop: "{{ user_ssh_keys }}"
  loop_control:
    label: "{{ item }}.pub"

- name: ssh ~> Ensure ssh key added to agent
  ansible.builtin.shell:
    cmd: eval $(ssh-agent -s) && ssh-add {{ user_home }}/.ssh/{{ item | basename }}
  changed_when: false
  become: true
  become_user: "{{ user }}"
  loop: "{{ user_ssh_keys }}"
