---
bash: yes
bashrc: "{{ user_home }}/.bashrc"

zsh: yes
zsh_profile: "{{ user_home }}/.zprofile"
zshrc: "{{ user_home }}/.zshrc"

fish: yes
fish_bin: /usr/bin/fish
fish_config: "{{ user_home }}/.local/fish/config.fish"


omf: false
omf_theme: ""
omf_packages: []
omf_target_dir: "{{ user_home }}/.local/share/omf"

omz: false
omz_theme: ""
