---
- name: gpg ~> Ensure keys imported
  block:
    - name: gpg ~> Check key stat
      ansible.builtin.command:
        cmd: gpg --list-secret-keys --keyid-format LONG
      changed_when: false
      failed_when: false
      register: _gpg

    - name: gpg ~> Set import facts
      ansible.builtin.set_fact:
        gpg_do_import: "{{ gpg.id not in _gpg.stdout }}"

    - name: gpg ~> Copy gpg key
      ansible.builtin.copy:
        src: "{{ gpg.file }}"
        dest: "/tmp/{{ gpg.id }}.key"
        mode: "0600"
      when: gpg_do_import

    - name: Import gpg keys
      ansible.builtin.command:
        cmd: gpg --import /tmp/{{ gpg.id }}.key
      when: gpg_do_import

    - name: Ensure gpg key file deleted
      ansible.builtin.file:
        path: "/tmp/{{ gpg.id }}.key"
        state: absent
  become: true
  become_user: "{{ user }}"
