---
- name: gpg ~> Ensure keys imported
  block:
    - name: gpg ~> Check key stat
      ansible.builtin.command:
        cmd: gpg --list-secret-keys --keyid-format LONG
      changed_when: false
      register: _gpg

    - name: gpg ~> Set import facts
      ansible.builtin.set_fact:
        ws_gpg_do_import: "{{ ws_gpg.id not in _gpg.stdout }}"

    - name: gpg ~> Copy gpg key
      ansible.builtin.copy:
        content: "{{ lookup('community.sops.sops', ws_encrypted_dir + '/' + ws_gpg.file, rstrip=false) }}"
        dest: "/tmp/{{ ws_gpg.id }}.key"
        mode: "0600"
      when: ws_gpg_do_import

    - name: Import gpg keys
      ansible.builtin.command:
        cmd: gpg --import /tmp/{{ ws_gpg.id }}.key
      when: ws_gpg_do_import

    - name: Ensure gpg key file deleted
      ansible.builtin.file:
        path: "/tmp/{{ ws_gpg.id }}.key"
        state: absent
  become: true
  become_user: "{{ ws_user }}"
