---
- name: vagrant ~> Ensure setup task executed
  ansible.builtin.include_tasks: vagrant/setup-{{ os_family }}.yml

- name: vagrant ~> Ensure package installed
  ansible.builtin.package:
    name: vagrant
    state: present
