---
- name: chezmoi add bashrc
  ansible.builtin.command:
    cmd: "{{ chezmoi_bin }} add {{ bashrc }}"
  changed_when: false
  become: true
  become_user: "{{ user }}"

- name: chezmoi add profile
  ansible.builtin.command:
    cmd: "{{ chezmoi_bin }} add {{ bash_profile }}"
  changed_when: false
  become: true
  become_user: "{{ user }}"

- name: chezmoi add fish
  ansible.builtin.command:
    cmd: "{{ chezmoi_bin }} add {{ fish_config }}"
  changed_when: false
  become: true
  become_user: "{{ user }}"

- name: chezmoi add zshrc
  ansible.builtin.command:
    cmd: "{{ chezmoi_bin }} add {{ zshrc }}"
  changed_when: false
  become: true
  become_user: "{{ user }}"

- name: chezmoi add zprofile
  ansible.builtin.command:
    cmd: "{{ chezmoi_bin }} add {{ zsh_profile }}"
  changed_when: false
  become: true
  become_user: "{{ user }}"
