---
- name: phpbrew ~> Ensure installed
  block:
    - name: phpbrew ~> Ensure installed
      when: phpbrew_install
      ansible.builtin.shell:
        cmd: >
          mkdir -p {{ phpbrew_bin | dirname }}
          && curl -k -L -O https://github.com/phpbrew/phpbrew/releases/download/{{ phpbrew_version }}/phpbrew.phar
          && chmod +x phpbrew.phar
          && mv phpbrew.phar {{ phpbrew_bin }}
        creates: "{{ phpbrew_bin }}"
        chdir: "{{ user_home }}"
      register: stat
      retries: 5
      delay: 3
      until: 0 == stat.rc

    - name: phpbrew ~> Ensure bash loaded
      ansible.builtin.blockinfile:
        marker_begin: <phpbrew>
        marker_end: </phpbrew>
        dest: "{{ bashrc }}"
        block: |
          [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
      notify: chezmoi add bashrc

    - name: phpbrew ~> Ensure zsh loaded
      when: zsh
      ansible.builtin.blockinfile:
        marker_begin: <phpbrew>
        marker_end: </phpbrew>
        dest: "{{ zshrc }}"
        block: |
          [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
      notify: chezmoi add zshrc

    - name: phpbrew ~> Ensure init script configured
      ansible.builtin.blockinfile:
        marker_begin: <phpbrew>
        marker_end: </phpbrew>
        dest: "{{ zshrc }}"
        block: "{{ lookup('template', 'phpbrew.init.j2') }}"
        create: yes
        owner: "{{ user }}"
        group: "{{ user_group }}"
        mode: "0644"
      notify: chezmoi add fish
  become: true
  become_user: "{{ user }}"
