---
- name: phpbrew ~> Ensure installed
  block:
    - name: phpbrew ~> Ensure installed
      when: phpbrew_install
      ansible.builtin.shell:
        cmd: >
          mkdir -p {{ phpbrew_bin | dirname }}
          && curl -k -L -O https://github.com/phpbrew/phpbrew/releases/download/{{ phpbrew_version }}/phpbrew.phar
          && chmod +x phpbrew.phar
          && mv phpbrew.phar {{ phpbrew_bin }}
        creates: "{{ phpbrew_bin }}"
        chdir: "{{ user_home }}"
      register: stat
      retries: 5
      delay: 3
      until: 0 == stat.rc

    - name: phpbrew ~> Ensure initialized
      when: not phpbrew_install
      ansible.builtin.shell:
        cmd: "{{ phpbrew_bin }} init"
        creates: "{{ phpbrew_home }}/bashrc"

    - name: phpbrew ~> Ensure bash configured
      ansible.builtin.blockinfile:
        marker_begin: <> phpbrew
        marker_end: </> phpbrew
        dest: "{{ bashrc }}"
        block: |
          [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
      notify: chezmoi add bashrc

    - name: phpbrew ~> Ensure zsh configured
      when: zsh
      ansible.builtin.blockinfile:
        marker_begin: <> phpbrew
        marker_end: </> phpbrew
        dest: "{{ zshrc }}"
        block: |
          [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
      notify: chezmoi add zshrc

    - name: phpbrew ~> Ensure fish configured
      when: fish
      ansible.builtin.blockinfile:
        marker_begin: <> phpbrew
        marker_end: </> phpbrew
        dest: "{{ fish_config }}"
        block: |
          source ~/.phpbrew/phpbrew.fish
      notify: chezmoi add fish

    - name: phpbrew ~> Ensure init script configured
      ansible.builtin.blockinfile:
        marker_begin: <> phpbrew
        marker_end: </> phpbrew
        dest: "{{ phpbrew_home }}/init"
        block: "{{ lookup('template', 'phpbrew.init.j2') }}"
        create: yes
        owner: "{{ user }}"
        group: "{{ user_group }}"
        mode: "0644"
  become: true
  become_user: "{{ user }}"

- name: phpbrew ~> Ensure brew environment configured
  block:
    - name: phpbrew ~> Ensure using system php
      ansible.builtin.command:
        cmd: "{{ brew_bin }} unlink php@8.1"
        removes: "{{ brew_prefix }}/bin/php"
  become: true
  become_user: "{{ user }}"
  when: not phpbrew_install
