---
- name: Ensure facts tasks executed
  ansible.builtin.include_tasks:
    file: facts.yml
    apply:
      tags: facts
  tags: facts

- name: Ensure build tasks executed
  ansible.builtin.include_tasks:
    file: build.yml
    apply:
      tags: build
  tags: build
