---
- name: Ensure proxy
  ansible.builtin.include_tasks: verify/ensure-proxy.yml

- name: Ensure configuration validated
  ansible.builtin.include_role:
    name: "{{ role_item }}"
    tasks_from: preflight
    public: true
  loop:
    - user
  loop_control:
    loop_var: "role_item"
