---
- name: Include install tasks
  ansible.builtin.include_tasks: setup.yml
  when: brew_install

- name: Include install package tasks
  ansible.builtin.include_tasks: setup-packages.yml
  when: brew

- name: Ensure shell configured
  ansible.builtin.include_tasks:
    file: shell.yml
    apply:
      become: true
      become_user: "{{ user }}"
