---
- name: Ensure brew home exists
  ansible.builtin.file:
    path: "{{ brew_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Start installation
  block:
    - name: Download install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/brew-install.sh
        mode: "0775"
        validate_certs: no

    - name: Execute install script
      ansible.builtin.command:
        cmd: /tmp/brew-install.sh
        creates: "{{ brew_bin }}"
      environment:
        NONINTERACTIVE: 1
      register: stat
      retries: 5
      delay: 3
      until: stat.rc == 0

  become: true
  become_user: "{{ user }}"
