---
- name: Install development tools on RedHat family os
  ansible.builtin.yum:
    name: '@Development tools'
    state: present
  when: os_family == 'RedHat'

- name: Ensure brew home exists
  ansible.builtin.file:
    path: "{{ brew_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0755"

- name: Ensure brew installed
  block:
    - name: Ensure install scripts downloaded
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/brew-install.sh
        mode: "0775"
        validate_certs: no

    - name: Ensure brew installed
      ansible.builtin.cmd:
        cmd: /tmp/brew-install.sh
        creates: "{{ brew_bin }}"
      environment:
        NONINTERACTIVE: 1
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        HOMEBREW_BREW_GIT_REMOTE: "{{ homebrew_brew_git_remote }}"
        HOMEBREW_CORE_GIT_REMOTE: "{{ homebrew_core_git_remote }}"
      register: stat
      retries: 5
      delay: 3
      until: stat.rc == 0

  become: true
  become_user: "{{ user }}"
