---
- debug: var=ws_encrypted_files
- name: decrypt ~> Decrypt secret files
  block:
    - name: decrypt ~> Ensure decrypted file dir exists
      ansible.builtin.file:
        path: "files/{{ item|dirname }}"
        state: directory
        mode: "0755"
        owner: "{{ ws_user }}"
        group: "{{ ws_user_group }}"
      loop: "{{ ws_encrypted_files }}"

    - name: decrypt ~> Ensure decrypted file exists
      ansible.builtin.copy:
        content: "{{ lookup('community.sops.sops', 'files/.encrypted/{{ item }}', rstrip=false) }}"
        dest: "files/{{ item }}"
        owner: "{{ ws_user }}"
        group: "{{ ws_user_group }}"
      loop: "{{ ws_encrypted_files }}"
      delegate_to: localhost
      become: false

    - name: encrypt ~> Ensure secrets file ignored
      ansible.builtin.include_tasks: sops-ignore.yml
  when: ws_encrypted_files | length > 0
