---
- name: Build Workstation
  hosts: all
  become: true
  gather_facts: true
  roles:
    - kilip.workstation.build
  vars:
    ws_user: toni
    ws_user_ssh_keys:
      - id_rsa
    ws_user_gpg_keys:
      - file: gpg-3C9B6EBE88D163FA.key
      - file: gpg-40A29F572C8134B1.key
    ws_proxy: "{{ lookup('env', 'WS_PROXY') }}"
    ws_proxy_cert: "{{ lookup('env', 'WS_PROXY_CERT') }}"
    brew_packages:
      - direnv
      - chezmoi
      - pyenv
      - phpbrew
    brew_enabled: yes
