---
- name: Build Workstation
  hosts: all
  become: true
  gather_facts: true
  environment:
    TAGS_RUN: preflight
  roles:
    - kilip.workstation.build
  vars:
    ws_user: toni
    ws_proxy_cert: "{{ lookup('env','WS_PROXY_CERT') }}"
    ws_proxy: "{{ lookup('env','WS_PROXY') }}"
    ws_encrypted_files:
      - squid-cert.crt
      #- id_rsa
      - id_rsa.pub
