---
- name: Build Workstation
  hosts: all
  become: true
  gather_facts: true
  roles:
    - kilip.workstation.build
  vars:
    # only runs this long running tasks when package changes
    brew: "{{ lookup('env', 'WS_BREW') }}"
    regolith: "{{ lookup('env', 'WS_REGOLITH') }}"
    shell: "{{ lookup('env', 'WS_SHELL') }}"
    desktop: "{{ lookup('env', 'WS_DESKTOP') }}"
    development: "{{ lookup('env', 'WS_DEVELOPMENT') }}"
