---
- name: Build Workstation
  hosts: all
  become: true
  gather_facts: true
  collections:
    - kilip.workstation
  roles:
    - preflight
    - user
    - shell
    - brew
    - development
    - desktop
