build_brew: "{{ lookup('env', 'WS_BREW') | bool }}"
build_shell: "{{ lookup('env', 'WS_SHELL') | bool }}"
build_desktop: "{{ lookup('env', 'WS_DESKTOP') | bool }}"
build_development: "{{ lookup('env', 'WS_DEVELOPMENT') | bool }}"

user: toni
user_ssh_keys:
  - ssh/id_rsa
user_gpg_keys:
  - file: gpg/gpg-3C9B6EBE88D163FA.key
  - file: gpg/gpg-40A29F572C8134B1.key
user_shell: "/usr/bin/fish"

git_config:
  - name: user.name
    value: Anthonius Munthi
  - name: user.email
    value: me@itstoni.com
  - name: commit.gpgSign
    value: true
  - name: core.excludesFile
    value: "~/.gitignore"
  - name: user.signingKey
    value: 3C9B6EBE88D163FA
  - name: pull.rebase
    value: true

proxy: "{{ lookup('env', 'WS_PROXY') }}"
proxy_cert: "{{ lookup('env', 'WS_PROXY_CERT') }}"

omf: yes
omf_theme: bobthefish

omz: yes
omz_theme: agnoster

brew_packages:
  - direnv
  - chezmoi

chezmoi_repo: git@github.com:kilip/molecule-dotfiles.git

phpbrew: yes
pyenv: yes
vscode: "{{ lookup('env', 'WS_VSCODE') | bool }}"
virtualbox: "{{ lookup('env', 'WS_VIRTUALBOX') | bool }}"
vagrant: "{{ lookup('env', 'WS_VAGRANT') | bool }}"

google_chrome: "{{ lookup('env', 'WS_GOOGLE_CHROME') | bool }}"
regolith: "{{ lookup('env', 'WS_REGOLITH') | bool }}"
