---
- name: proxy ~> Ensure cert file copied
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', ws_proxy_cert, rstrip=false) }}"
    dest: "{{ ws_cert_path }}/{{ ws_proxy_cert|basename }}"
    mode: "0644"
  when: ansible_os_family == 'Debian'

- name: proxy ~> Ensure cert file copied on RedHat family OS
  ansible.builtin.copy:
    src: "{{ ws_proxy_cert }}"
    dest: "/etc/ssl/certs/{{ ws_proxy_cert | basename | replace('.crt', '.pem') }}"
    mode: "0644"
  when: ansible_os_family == 'RedHat'

- name: proxy ~> Ensure update ca-certificates command executed
  ansible.builtin.command:
    cmd: "{{ ws_update_cert_command }}"
    creates: "{{ ws_proxy_cert_path }}"
  register: out
  changed_when: false
