---
- name: Ensure "{{ ansible_os_family }}" configured
  ansible.builtin.include_vars: config-{{ ansible_os_family }}.yml

- name: Ensure proxy fact configured
  ansible.builtin.set_fact:
    proxy_build: "{{ proxy | length > 0 }}"
    proxy_cert_build: "{{ proxy_cert | length > 0 }}"

- name: Ensure common package installed
  kilip.workstation.add_package:
    package:
      - git
      - curl
