---
- name: Ensure proxy configured
  ansible.builtin.include_tasks: proxy/setup.yml
  when: proxy_build

- name: Ensure OS updated
  ansible.builtin.include_tasks: "dist/setup-{{ os_family }}.yml"

- name: Ensure packages installed
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

# fix linuxbrew install when using proxy with ssl bump
- name: Ensure git http.sslVerify disabled
  community.general.git_config:
    scope: system
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: http.postBuffer
      value: 1048576000
    - name: http.sslVerify
      value: false
  when: proxy_cert_build
