---
- name: omf ~> Ensure current omf stat checked
  ansible.builtin.stat:
    path: "{{ omf_target_dir }}"
  register: _omf

- name: omf ~> Ensure installed
  ansible.builtin.include_tasks:
    file: setup-Linux.yml
    apply:
      become: true
      become_user: "{{ user }}"
  when: not _omf.stat.exists

- name: omf ~> Ensure package installed
  ansible.builtin.command:
    cmd: "omf install {{ item }}"
    creates: "{{ omf_target_dir }}/pkg/{{ item }}"
    chdir: "{{ user_home }}"
    executable: /usr/bin/fish
  loop: "{{ omf_packages }}"
  become: true
  become_user: "{{ user }}"

- name: omf ~> Ensure theme installed
  ansible.builtin.command:
    cmd: "omf install {{ omf_theme }}"
    creates: "{{ omf_target_dir }}/themes/{{ omf_theme }}"
    chdir: "{{ user_home }}"
    executable: /usr/bin/fish
  when: omf_theme | length > 0
  become: true
  become_user: "{{ user }}"
