---
- name: omf ~> Ensure install script downloaded
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    dest: /tmp/omf-install
    validate_certs: "{{ not ws_proxy_cert_build }}"

- name: omf ~> Execute install script
  ansible.builtin.command:
    cmd: fish /tmp/omf-install --noninteractive
    creates: "{{ omf_target_dir }}/init.fish"
