name: CI

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    paths:
      - roles/brew/**
    branches:
      - main
  pull_request:
    paths:
      - roles/brew/**
    branches:
      - main
  # Run CI once per day (at 05:15 UTC)
  schedule:
    - cron: '15 5 * * *'

defaults:
  run:
    working-directory: ansible_collections/kilip/workstation

env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  molecule:
    runs-on: ubuntu-latest
    name: "Scenario ${{ matrix.scenario }}@${{ matrix.dist }}"
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
        dist:
          - ubuntu-22.04
          - debian-11
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/kilip/workstation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install test requirements
        run: pip install -r requirements.txt

      - name: Create default collection path symlink
        run: |
          mkdir -p /home/runner/.ansible
          ln -s /home/runner/work/workstation/workstation /home/runner/.ansible/collections

      - name: Configure age key
        run: |
          mkdir -p ~/.config/sops/age
          cp molecule/default/files/age.key ~/.config/sops/age/keys.txt

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.2.0

      - name: Run molecule test
        run: molecule test -s ${{ matrix.scenario}}
        env:
          MOLECULE_DIST: ${{ matrix.dist }}
          WS_BREW: 1
